USE [SUCURSAL1]
GO

CREATE USER[GERENTE1] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER[AUDITOR] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE ROLE GERENTE
GO

GRANT SELECT ON SUCURSAL1.dbo.INVENTARIO, SUCURSAL1.dbo.DETALLEINVENTARIO, SUCURSAL1.dbo.PROVEEDORES, SUCURSAL1.dbo.PROVEEDORES_CORREOS,
SUCURSAL1.dbo.TELEFONOS, SUCURSAL1.dbo.TIPOPAGO, SUCURSAL1.dbo.CATEGORIAS to GERENTE

GRANT UPDATE, DELETE, SELECT ON SUCURSAL1.dbo.FACTURAS, SUCURSAL1.dbo.DETALLEFACTURA, SUCURSAL1.dbo.EMPLEADOS, SUCURSAL1.dbo.EMPLEADOS_TELEFONOS,
SUCURSAL1.dbo.EMPLEADOS_CORREOS to GERENTE

GRANT GERENTE TO GERENTE1;
GO

CREATE VIEW EMPLEADOSVIEW AS SELECT idEmpleado, nombre, direccion, rol from EMPLEADOS;
GRANT SELECT TO AUDITOR ON EMPLEADOSVIEW;

GRANT SELECT TO AUDITOR ON FACTURAS;
GRANT SELECT TO AUDITOR ON DETALLEFACTURA;
GRANT SELECT TO AUDITOR ON EMPLEADOS_TELEFONOS;
GRANT SELECT TO AUDITOR ON EMPLEADOS_CORREOS;
GO
--------------------------------------------------------------------------------------------------------------------------------------------------
USE [SUCURSAL2]
GO

CREATE USER[GERENTE1] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER[AUDITOR] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE ROLE GERENTE
GO

GRANT SELECT ON SUCURSAL1.dbo.INVENTARIO, SUCURSAL2.dbo.DETALLEINVENTARIO, SUCURSAL2.dbo.PROVEEDORES, SUCURSAL2.dbo.PROVEEDORES_CORREOS,
SUCURSAL2.dbo.TELEFONOS, SUCURSAL2.dbo.TIPOPAGO, SUCURSAL2.dbo.CATEGORIAS to GERENTE

GRANT UPDATE, DELETE, SELECT ON SUCURSAL2.dbo.FACTURAS, SUCURSAL2.dbo.DETALLEFACTURA, SUCURSAL2.dbo.EMPLEADOS, SUCURSAL2.dbo.EMPLEADOS_TELEFONOS,
SUCURSAL2.dbo.EMPLEADOS_CORREOS to GERENTE

GRANT GERENTE TO GERENTE1;
GO

CREATE VIEW EMPLEADOSVIEW AS SELECT idEmpleado, nombre, direccion, rol from EMPLEADOS;
GRANT SELECT TO AUDITOR ON EMPLEADOSVIEW;

GRANT SELECT TO AUDITOR ON FACTURAS;
GRANT SELECT TO AUDITOR ON DETALLEFACTURA;
GRANT SELECT TO AUDITOR ON EMPLEADOS_TELEFONOS;
GRANT SELECT TO AUDITOR ON EMPLEADOS_CORREOS;

GO
------------------------------------------------------------------------------------------------------------------------------------------------------
USE [CENTRAL]
GO

CREATE USER[GERENTE1] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER[AUDITOR] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[SUCURSAL1], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE ROLE GERENTE
GO

GRANT UPDATE, DELETE,SELECT ON CENTRAL.dbo.INVENTARIO, CENTRAL.dbo.DETALLEINVENTARIO, CENTRAL.dbo.PROVEEDORES, CENTRAL.dbo.PROVEEDORES_CORREOS,
CENTRAL.dbo.TELEFONOS, CENTRAL.dbo.TIPOPAGO, CENTRAL.dbo.CATEGORIAS to GERENTE

GRANT SELECT ON CENTRAL.dbo.FACTURAS, CENTRAL.dbo.DETALLEFACTURA, CENTRAL.dbo.EMPLEADOS, CENTRAL.dbo.EMPLEADOS_TELEFONOS,
CENTRAL.dbo.EMPLEADOS_CORREOS to GERENTE

GRANT GERENTE TO GERENTE1;
GO

CREATE VIEW INVENTARIOVIEW AS SELECT idProducto, nombre, descripcion, precioVenta, categoria;
GRANT SELECT TO AUDITOR ON INVENTARIOVIEW

GRANT SELECT TO AUDITOR ON DETALLEINVENTARIO;
GRANT SELECT TO AUDITOR ON PROVEEDORES;
GRANT SELECT TO AUDITOR ON PROVEEDORES_TELEFONOS;
GRANT SELECT TO AUDITOR ON PROVEEDORES_CORREOS;
GRANT SELECT TO AUDITOR ON TIPOCATEGORIA;
GRANT SELECT TO AUDITOR ON SUCURSAL;

GO