/*
	CREACIÓN DE USUARIO ADMINISTRADOR DE LA FARMACIA #2.
*/
USE [master]
GO
CREATE LOGIN [FARMACIA2] WITH PASSWORD=N'ucr2019', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [FARMACIA1]
GO

/*
	CREACIÓN DE LA BASE DE DATOS #2; DE LA FARMACIA #2.
*/

CREATE DATABASE [SUCURSAL2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUCURSAL2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SUCURSAL2.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SUCURSAL2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SUCURSAL2_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SUCURSAL2] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [SUCURSAL2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SUCURSAL2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SUCURSAL2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SUCURSAL2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SUCURSAL2] SET ARITHABORT OFF 
GO
ALTER DATABASE [SUCURSAL2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SUCURSAL2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SUCURSAL2] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SUCURSAL2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SUCURSAL2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SUCURSAL2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SUCURSAL2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SUCURSAL2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SUCURSAL2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SUCURSAL2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SUCURSAL2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SUCURSAL2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SUCURSAL2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SUCURSAL2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SUCURSAL2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SUCURSAL2] SET  READ_WRITE 
GO
ALTER DATABASE [SUCURSAL2] SET RECOVERY FULL 
GO
ALTER DATABASE [SUCURSAL2] SET  MULTI_USER 
GO
ALTER DATABASE [SUCURSAL2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SUCURSAL2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SUCURSAL2] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SUCURSAL2]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SUCURSAL2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SUCURSAL2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/*
	CREACIÓN DE TABLAS DE LA SUCURSAL #2.
*/
USE [SUCURSAL2]
GO

/*
	PARA HACER REFERENCIA A LA FARMACIA #2, SE HACE A TRAVÉS DEL CÓDIGO DE FARMACIA 2, EN LA BASE DE DATOS CENTRAL.
*/

CREATE TABLE EMPLEADOS
(idEmpleado int,
nombre varchar(50),
direccion varchar(100),
salario decimal(10,2),
rol varchar(10),
idFarmacia int default (2),
PRIMARY KEY (idEmpleado))
GO

CREATE TABLE EMPLEADOS_TELEFONOS
(idEmpleado int,
telefono varchar(20),
idFarmacia int default (2),
PRIMARY KEY (idEmpleado, telefono),
FOREIGN KEY (idEmpleado) REFERENCES EMPLEADOS(idEmpleado))
GO

CREATE TABLE EMPLEADOS_CORREOS
(idEmpleado int,
correo varchar(50),
idFarmacia int default (2),
PRIMARY KEY (idEmpleado, correo),
FOREIGN KEY (idEmpleado) REFERENCES EMPLEADOS(idEmpleado))
GO

CREATE TABLE CATEGORIAS
(idCategoria int,
nombre varchar(20),
PRIMARY KEY(idCategoria))
GO

CREATE TABLE PROVEEDORES
(idProveedor int,
nombre varchar(50),
direccion varchar(100),
descripcion varchar(50),
PRIMARY KEY (idProveedor))
GO

CREATE TABLE PROVEEDORES_TELEFONOS
(idProveedor int,
telefono varchar(20),
PRIMARY KEY (idProveedor, telefono),
FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor))
GO

CREATE TABLE PROVEEDORES_CORREOS
(idProveedor int,
correo varchar(50),
PRIMARY KEY (idProveedor, correo),
FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor))
GO

CREATE TABLE INVENTARIO
(idProducto int,
idCategoria int,
nombre varchar(20),
medida varchar(10),
precioVenta decimal(10,2),
precioCompra decimal(10,2),
descripcion varchar(50),
existencias int,
PRIMARY KEY (idProducto),
FOREIGN KEY (idCategoria) REFERENCES CATEGORIAS(idCategoria))
GO

CREATE TABLE DETALLEINVENTARIO
(idProducto int,
idProveedor int,
PRIMARY KEY(idProducto, idProveedor),
FOREIGN KEY (idProducto) REFERENCES INVENTARIO(idProducto),
FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor))
GO

CREATE TABLE TIPOPAGO
(idTipoPago int,
descripcion varchar(10)
PRIMARY KEY(idTipoPago))
GO

CREATE TABLE FACTURAS
(idFactura int,
fecha datetime,
montoTotal decimal(10,2),
idEmpleado int,
idFarmacia int default (2),
tipoPago int,
correo varchar(100),
IVA int,
IV int,
PRIMARY KEY (idFactura),
FOREIGN KEY(idEmpleado) REFERENCES EMPLEADOS(idEmpleado),
FOREIGN KEY(tipoPago) REFERENCES TIPOPAGO(idTipoPago))
GO

CREATE TABLE DETALLEFACTURA
(idFactura int,
idProducto int,
costo decimal(10,2),
cantidad int,
subtotal decimal(10,2),
idFarmacia int default (2),
PRIMARY KEY(idFactura, idProducto),
FOREIGN KEY(idFactura) REFERENCES FACTURAS(idFactura),
FOREIGN KEY(idProducto) REFERENCES INVENTARIO(idProducto))
GO

CREATE TABLE USUARIOS
(usuario varchar(20),
contrasena varchar(20),
rol varchar(20),
idEmpleado int,
PRIMARY KEY(usuario),
FOREIGN KEY(idEmpleado) REFERENCES Empleados(idEmpleado));
GO

CREATE TABLE EMP_ING_ACT_ELI
(idEmpleado int,
tipo char(1))
GO

CREATE TABLE EMP_CORREO_ING_ACT_ELI
(idEmpleado int,
correo varchar(50),
tipo char(1))
GO

CREATE TABLE EMP_TEL_ING_ACT_ELI
(idEmpleado int,
telefono varchar(20),
tipo char(1))
GO

CREATE TABLE FACT_ING_ACT_ELI
(idFactura int,
tipo char(1));
GO

CREATE TABLE DET_FACT_ING_ACT_ELI
(idFactura int,
idProducto int,
tipo char(1))
GO